<?php

namespace LaraGram\Support\Facades;

use LaraGram\Laraquest\Mode;

/**
 * @method static mode(Mode|int $mode)
 * @method static getUpdates($offset = null, $limit = null, $timeout = null, $allowed_updates = null)
 * @method static setWebhook($url, $certificate = null, $ip_address = null, $max_connections = null, $allowed_updates = null, $drop_pending_updates = null, $secret_token = null)
 * @method static deleteWebhook($drop_pending_updates = null)
 * @method static getWebhookInfo()
 * @method static getMe()
 * @method static logOut()
 * @method static close()
 * @method static sendMessage($chat_id, $text, $parse_mode = null, $message_thread_id = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $link_preview_options = null, $entities = null, $business_connection_id = null, $message_effect_id = null)
 * @method static forwardMessage($chat_id, $from_chat_id, $message_id, $message_thread_id = null, $protect_content = null, $disable_notification = null)
 * @method static forwardMessages($chat_id, $from_chat_id, $message_ids, $message_thread_id = null, $protect_content = null, $disable_notification = null)
 * @method static copyMessage($chat_id, $from_chat_id, $message_id, $parse_mode = null, $message_thread_id = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $caption = null, $caption_entities = null, $show_caption_above_media = null)
 * @method static copyMessages($chat_id, $from_chat_id, $message_ids, $message_thread_id = null, $protect_content = null, $disable_notification = null, $remove_caption = null)
 * @method static sendPhoto($chat_id, $photo, $caption = null, $parse_mode = null, $message_thread_id = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $has_spoiler = null, $caption_entities = null, $show_caption_above_media = null, $message_effect_id = null, $business_connection_id = null)
 * @method static sendAudio($chat_id, $audio, $caption = null, $parse_mode = null, $message_thread_id = null, $duration = null, $performer = null, $title = null, $thumbnail = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $caption_entities = null, $business_connection_id = null, $message_effect_id = null)
 * @method static sendDocument($chat_id, $document, $caption = null, $parse_mode = null, $message_thread_id = null, $thumbnail = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $caption_entities = null, $business_connection_id = null, $disable_content_type_detection = null, $message_effect_id = null)
 * @method static sendVideo($chat_id, $video, $caption = null, $parse_mode = null, $message_thread_id = null, $duration = null, $width = null, $height = null, $thumbnail = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $caption_entities = null, $show_caption_above_media = null, $has_spoiler = null, $supports_streaming = null, $business_connection_id = null, $message_effect_id = null)
 * @method static sendAnimation($chat_id, $animation, $caption = null, $parse_mode = null, $message_thread_id = null, $duration = null, $width = null, $height = null, $thumbnail = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $caption_entities = null, $show_caption_above_media = null, $has_spoiler = null, $business_connection_id = null, $message_effect_id = null)
 * @method static sendVoice($chat_id, $voice, $caption = null, $parse_mode = null, $message_thread_id = null, $duration = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $caption_entities = null, $business_connection_id = null, $message_effect_id = null)
 * @method static sendVideoNote($chat_id, $video_note, $message_thread_id = null, $duration = null, $length = null, $thumbnail = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $business_connection_id = null, $message_effect_id = null)
 * @method static sendPaidMedia($chat_id, $star_count, $media, $caption = null, $pars_mode = null, $caption_entities = null, $show_caption_above_media = null, $disable_notification = null, $protect_content = null, $reply_parameters = null, $reply_markup = null, $business_connection_id  = null)
 * @method static sendMediaGroup($chat_id, $media, $message_thread_id = null, $reply_parameters = null, $protect_content = null, $disable_notification = null, $business_connection_id = null, $message_effect_id = null)
 * @method static sendLocation($chat_id, $latitude, $longitude, $horizontal_accuracy = null, $live_period = null, $heading = null, $proximity_alert_radius = null, $message_thread_id = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $business_connection_id = null, $message_effect_id = null)
 * @method static sendVenue($chat_id, $latitude, $longitude, $title, $address, $foursquare_id = null, $foursquare_type = null, $google_place_id = null, $google_place_type = null, $message_thread_id = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $business_connection_id = null, $message_effect_id = null)
 * @method static sendContact($chat_id, $phone_number, $first_name, $last_name = null, $vcard = null, $message_thread_id = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $business_connection_id = null, $message_effect_id = null)
 * @method static sendPoll($chat_id, $question, $options, $is_anonymous = null, $type = null, $allows_multiple_answers = null, $question_parse_mode = null, $question_entities = null, $correct_option_id = null, $explanation = null, $explanation_parse_mode = null, $explanation_entities = null, $open_period = null, $close_date = null, $is_closed = null, $message_thread_id = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $business_connection_id = null, $message_effect_id = null)
 * @method static sendDice($chat_id, $emoji = null, $message_thread_id = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $business_connection_id = null, $message_effect_id = null)
 * @method static sendChatAction($chat_id, $action, $message_thread_id = null, $business_connection_id = null)
 * @method static setMessageReaction($chat_id, $message_id, $reaction = null, $is_big = null)
 * @method static getUserProfilePhotos($user_id, $offset = null, $limit = null)
 * @method static getFile($file_id)
 * @method static banChatMember($chat_id, $user_id, $until_date = null, $revoke_messages = null)
 * @method static unbanChatMember($chat_id, $user_id, $only_if_banned = null)
 * @method static restrictChatMember($chat_id, $user_id, $permissions, $until_date = null, $use_independent_chat_permissions = null)
 * @method static promoteChatMember($chat_id, $user_id, $is_anonymous = null, $can_manage_chat = null, $can_delete_messages = null, $can_manage_video_chats = null, $can_restrict_members = null, $can_promote_members = null, $can_change_info = null, $can_invite_users = null, $can_post_stories = null, $can_edit_stories = null, $can_delete_stories = null, $can_post_messages = null, $can_edit_messages = null, $can_pin_messages = null, $can_manage_topics = null)
 * @method static setChatAdministratorCustomTitle($chat_id, $user_id, $title)
 * @method static banChatSenderChat($chat_id, $sender_chat_id)
 * @method static unbanChatSenderChat($chat_id, $sender_chat_id)
 * @method static setChatPermissions($chat_id, $permissions, $use_independent_chat_permissions = null)
 * @method static exportChatInviteLink($chat_id)
 * @method static createChatInviteLink($chat_id, $name = null, $expire_date = null, $member_limit = null, $creates_join_request = null)
 * @method static editChatInviteLink($chat_id, $invite_link, $name = null, $expire_date = null, $member_limit = null, $creates_join_request = null)
 * @method static revokeChatInviteLink($chat_id, $invite_link)
 * @method static approveChatJoinRequest($chat_id, $user_id)
 * @method static declineChatJoinRequest($chat_id, $user_id)
 * @method static setChatPhoto($chat_id, $photo)
 * @method static deleteChatPhoto($chat_id)
 * @method static setChatTitle($chat_id, $title)
 * @method static setChatDescription($chat_id, $description)
 * @method static pinChatMessage($chat_id, $message_id, $disable_notification = null, $business_connection_id = null)
 * @method static unpinChatMessage($chat_id, $message_id, $business_connection_id = null)
 * @method static unpinAllChatMessages($chat_id)
 * @method static leaveChat($chat_id)
 * @method static getChat($chat_id)
 * @method static getChatAdministrators($chat_id)
 * @method static getChatMemberCount($chat_id)
 * @method static getChatMember($chat_id, $user_id)
 * @method static setChatStickerSet($chat_id, $sticker_set_name)
 * @method static deleteChatStickerSet($chat_id)
 * @method static getForumTopicIconStickers()
 * @method static createForumTopic($chat_id, $name, $icon_color = null, $icon_custom_emoji_id = null)
 * @method static editForumTopic($chat_id, $message_thread_id, $name = null, $icon_custom_emoji_id = null)
 * @method static closeForumTopic($chat_id, $message_thread_id)
 * @method static reopenForumTopic($chat_id, $message_thread_id)
 * @method static deleteForumTopic($chat_id, $message_thread_id)
 * @method static unpinAllForumTopicMessages($chat_id, $message_thread_id)
 * @method static editGeneralForumTopic($chat_id, $name)
 * @method static closeGeneralForumTopic($chat_id)
 * @method static reopenGeneralForumTopic($chat_id)
 * @method static hideGeneralForumTopic($chat_id)
 * @method static unhideGeneralForumTopic($chat_id)
 * @method static unpinAllGeneralForumTopicMessages($chat_id)
 * @method static answerCallbackQuery($callback_query_id, $text = null, $show_alert = null, $url = null, $cache_time = null)
 * @method static getUserChatBoosts($chat_id, $user_id)
 * @method static getBusinessConnection($business_connection_id)
 * @method static setMyCommands($commands, $scope = null, $language_code = null)
 * @method static deleteMyCommands($scope = null, $language_code = null)
 * @method static getMyCommands($scope = null, $language_code = null)
 * @method static setMyName($name = null, $language_code = null)
 * @method static getMyName($language_code = null)
 * @method static setMyDescription($description = null, $language_code = null)
 * @method static getMyDescription($language_code = null)
 * @method static setMyShortDescription($short_description = null, $language_code = null)
 * @method static getMyShortDescription($language_code = null)
 * @method static setChatMenuButton($chat_id = null, $menu_button = null)
 * @method static getChatMenuButton($chat_id = null)
 * @method static setMyDefaultAdministratorRights($rights = null, $for_channels = null)
 * @method static getMyDefaultAdministratorRights($for_channels = null)
 * @method static editMessageText($text, $chat_id = null, $message_id = null, $inline_message_id = null, $parse_mode = null, $entities = null, $link_preview_options = null, $reply_markup = null, $business_connection_id = null)
 * @method static editMessageCaption($chat_id = null, $message_id = null, $inline_message_id = null, $caption = null, $parse_mode = null, $caption_entities = null, $reply_markup = null, $show_caption_above_media = null, $business_connection_id = null)
 * @method static editMessageMedia($media, $chat_id = null, $message_id = null, $inline_message_id = null, $reply_markup = null, $business_connection_id = null)
 * @method static editMessageLiveLocation($latitude, $longitude, $chat_id = null, $message_id = null, $inline_message_id = null, $horizontal_accuracy = null, $heading = null, $proximity_alert_radius = null, $reply_markup = null, $live_period = null, $business_connection_id = null)
 * @method static stopMessageLiveLocation($chat_id = null, $message_id = null, $inline_message_id = null, $reply_markup = null, $business_connection_id = null)
 * @method static editMessageReplyMarkup($chat_id = null, $message_id = null, $inline_message_id = null, $reply_markup = null, $business_connection_id = null)
 * @method static stopPoll($chat_id, $message_id, $reply_markup = null, $business_connection_id = null)
 * @method static deleteMessage($chat_id, $message_id)
 * @method static deleteMessages($chat_id, $message_ids)
 * @method static sendSticker($chat_id, $sticker, $emoji = null, $message_thread_id = null, $reply_parameters = null, $reply_markup = null, $protect_content = null, $disable_notification = null, $business_connection_id = null, $message_effect_id = null)
 * @method static getStickerSet($name)
 * @method static getCustomEmojiStickers($custom_emoji_ids)
 * @method static uploadStickerFile($user_id, $sticker, $sticker_format)
 * @method static createNewStickerSet($user_id, $name, $title, $stickers, $sticker_type = null, $needs_repainting = null)
 * @method static addStickerToSet($user_id, $name, $sticker)
 * @method static setStickerPositionInSet($sticker, $position)
 * @method static deleteStickerFromSet($sticker)
 * @method static replaceStickerInSet($user_id, $name, $old_sticker, $sticker)
 * @method static setStickerEmojiList($sticker, $emoji_list)
 * @method static setStickerKeywords($sticker, $keywords = null)
 * @method static setStickerMaskPosition($sticker, $mask_position = null)
 * @method static setStickerSetTitle($name, $title)
 * @method static setStickerSetThumbnail($name, $user_id, $format, $thumbnail = null)
 * @method static setCustomEmojiStickerSetThumbnail($name, $custom_emoji_id = null)
 * @method static deleteStickerSet($name)
 * @method static answerInlineQuery($inline_query_id, $results, $cache_time = null, $is_personal = null, $next_offset = null, $button = null)
 * @method static answerWebAppQuery($web_app_query_id, $result)
 * @method static sendInvoice($chat_id, $title, $description, $payload, $provider_token, $currency, $price, $message_thread_id = null, $max_tip_amount = null, $suggested_tip_amounts = null, $start_parameter = null, $provider_data = null, $photo_url = null, $photo_size = null, $photo_width = null, $photo_height = null, $need_name = null, $need_phone_number = null, $need_email = null, $need_shipping_address = null, $send_phone_number_to_provider = null, $send_email_to_provider = null, $is_flexible = null, $disable_notification = null, $protect_content = null, $reply_parameters = null, $reply_markup = null, $message_effect_id = null)
 * @method static createInvoiceLink($title, $description, $payload, $provider_token, $currency, $price, $max_tip_amount = null, $suggested_tip_amounts = null, $provider_data = null, $photo_url = null, $photo_size = null, $photo_width = null, $photo_height = null, $need_name = null, $need_phone_number = null, $need_email = null, $need_shipping_address = null, $send_phone_number_to_provider = null, $send_email_to_provider = null, $is_flexible = null)
 * @method static answerShippingQuery($shipping_query_id, $ok, $shipping_options = null, $error_message = null)
 * @method static answerPreCheckoutQuery($pre_checkout_query_id, $ok, $error_message = null)
 * @method static getStarTransactions($offset = null, $limit = null)
 * @method static refundStarPayment($user_id, $telegram_payment_charge_id)
 * @method static setPassportDataErrors($user_id, $errors)
 * @method static sendGame($chat_id, $game_short_name, $message_thread_id = null, $disable_notification = null, $protect_content = null, $reply_parameters = null, $reply_markup = null, $business_connection_id = null, $message_effect_id = null)
 * @method static setGameScore($user_id, $score, $chat_id = null, $message_id = null, $inline_message_id = null, $disable_edit_message = null, $force = null)
 * @method static getGameHighScores($user_id, $chat_id = null, $message_id = null, $inline_message_id = null)
 * @method static createChatSubscriptionInviteLink($chat_id, $subscription_period, $subscription_price, $name = null)
 * @method static editChatSubscriptionInviteLink($chat_id, $invite_link, $name = null)
 * @method static getUpdateType()
 * @method static getUpdateMessageSubType(object $message)
 * @method static void macro(string $name, callable $macro)
 * @method static bool hasMacro(string $name)
 */
class Request extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor(): string
    {
        return 'laraquest';
    }
}